name: New Learning
favicon: null
layout_spectrum: 0.75102
typography_spectrum: 0.49864
title: New Learning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#084b8f'
    - '#656565'
    - '#73a8c7'
    - '#0492bc'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
